In [1]:
import random
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os
import math
from sklearn import metrics
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder, KBinsDiscretizer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
from time import sleep

pd.set_option('display.float_format', lambda x: '%.3f' % x)

sns.set()

In [2]:
def generaPath(tipo, nombre):
    prepath = str(os.getcwd())
    if (tipo == "I"):
        path = prepath + '\\origen\\' + nombre
    else :
        path = prepath + '\\generados\\' + nombre
    return path

In [3]:
df_tr_fu_filt_delta = pd.read_csv(generaPath('O', 'df_tr_fu_filt_delta.csv'))
df_re_fu_filt_delta = pd.read_csv(generaPath('O', 'df_re_fu_filt_delta.csv'))

In [4]:
conteos_1d_sb_tr = pd.read_csv(generaPath('O', 'conteos_1d_sb_tr.csv'))
conteos_1d_sb_re = pd.read_csv(generaPath('O', 'conteos_1d_sb_re.csv'))

In [5]:
conteos_1d_tr = pd.read_csv(generaPath('O', 'conteos_1d_tr.csv'))
conteos_1d_re = pd.read_csv(generaPath('O', 'conteos_1d_re.csv'))

In [6]:
conteos_2d_tr = pd.read_csv(generaPath('O', 'conteos_2d_tr.csv'))
conteos_2d_re = pd.read_csv(generaPath('O', 'conteos_2d_re.csv'))

In [7]:
conteos_3d_tr = pd.read_csv(generaPath('O', 'conteos_3d_tr.csv'))
conteos_3d_re = pd.read_csv(generaPath('O', 'conteos_3d_re.csv'))

In [8]:
conteos_4d_tr = pd.read_csv(generaPath('O', 'conteos_4d_tr.csv'))
conteos_4d_re = pd.read_csv(generaPath('O', 'conteos_4d_re.csv'))

In [9]:
conteos_5d_tr = pd.read_csv(generaPath('O', 'conteos_5d_tr.csv'))
conteos_5d_re = pd.read_csv(generaPath('O', 'conteos_5d_re.csv'))

#### Establezco los valores de inicio de los sorteos para calcular deltas

In [10]:
df_topes = df_tr_fu_filt_delta.iloc[0::1,[0]]
recent = df_topes.max()
print("sorteo mas reciente ", recent)
oldest = df_topes.min()
print("sorteo inicial ", oldest)

sorteo mas reciente  idSorteo    2093
dtype: int64
sorteo inicial  idSorteo    1671
dtype: int64

#### Se calcula los valores de diferencia entre los diversos sorteos

In [11]:
def calcular_deltas_verticales(df):
    delticas = []
    previo = recent
    for index, row in df.iterrows():
        resta = int(previo) - int(row[0])
        #print("resta : ", resta, " previo ", previo, " Sorteo: ", row[0], )
        delticas.append(int(resta))
        previo = int(row[0])
    resta = int(previo) - int(oldest)
    #print(resta)
    delticas.append(int(resta))
    return delticas

In [12]:
def unsplited_tupla(sbs):
    delticas = []
    partido = sbs.split(sep='|') if (sbs.find("|") >= 1) else sbs
    return partido

In [13]:
def calc_media(df):
    acum = 0
    media = 0
    length = len(df) 
    for i in range(length): 
        acum += int(df[i])
    media = int(acum/length)
    #print("valor de media: ", media)
    return media

In [14]:
def calc_moda(df):
    repetir = 0                                                                         
    for i in df:                                                                              
        aparece = df.count(i)                                                             
        if aparece > repetir:                                                       
            repetir = aparece 
    
    moda = []                                                                               
    for i in df:                                                                              
        aparece = df.count(i)
        #print("aparece ", aparece)
        if aparece == repetir and i not in moda:                                   
            moda.append(i) 
            #print("moda", moda)
            
    return moda

In [15]:
def calc_cant_moda(df_deltas, df_elected):
    #print(df_elected)
    num = str(df_elected[0])
    partido = num.split(sep='|') if (num.find("|") >= 1) else num
    
    #print(partido)
    repetir = 0                                                                         
    for i in df_deltas:
        #print("valor de i :", i)
        aparece = df_deltas.count(df_elected[0])   
        #print("valor de aparece:", aparece)
        if aparece > repetir:                                                       
            repetir = aparece 
    
    moda = []                                                                               
    for i in df_deltas:                                                                              
        aparece = df_deltas.count(i)
        #print("aparece ", aparece)
        if aparece == repetir and i not in moda:                                   
            moda.append(i) 
            #print("moda", moda)
    #print("fin ciclo", moda)        
    return moda

In [16]:
def sumarcol_peso(ldf):
    #print("valor de ldf", ldf)
    df = pd.DataFrame(ldf)
    #print("columna conteo ", df['conteo'])
    suma = ldf.sum()
    #suma = sumalista(df)
    print("valor de suma ", suma  )
    pesos = []                                                                               
    for index, row in df.iterrows():
        cant_tupla = int(row[0])
        #print("can_tupla ", cant_tupla)
        if cant_tupla > 0:
            dividido = cant_tupla /suma 
        pesos.append(float(dividido))  
    #print(type(pesos))
    return pesos

In [17]:
def sumalista(df):
    acum = 0
    #print("valor de listaNumeros ", df)
    for index, row in df.iterrows():
        cant_tupla = int(row[0])
        #print("can_tupla ", cant_tupla)
        acum = acum + cant_tupla
        print(acum)
    return acum

In [18]:
def entire_part(res1):
    pd, pe = math.modf(res1)
    #print("entire Part: ", pe, " decimal part: ", pd)
    if (int(pe) >= int(1)):
        res = pd
    else: 
        res = 1 - pd
    #print("res en entire_part", res)
    return res

In [19]:
def set_hot_level(last_number, evaluated_number ):
    #print("last:",int(last_number), " evaluated ",int(evaluated_number))
    if (int(last_number) > int(0) & int(evaluated_number) > int(0)):
        num = float(int(last_number) /int(evaluated_number))
    else:
        num = int(0)
    #print("num:", num)
    ret = entire_part(num)
    return ret

In [20]:
def set_closer_to_1(actual_number, new_number ):
    if actual_number >1:
        dif1 = float(actual_number - 1)
    else:
        dif1 = float(1 - actual_number)
    if new_number > 1:
        dif2 = float(new_number - 1)
    else:
        dif2 = float(1- new_number) 
    
    if dif1 > dif2:
        dif = new_number
    else:
        dif = actual_number
    return dif

In [21]:
def retorna_valor(valor):
    p2t = 0
    if float(valor) == float(0.0):
        p2t = float(0.3333)
    else:    
        p2t = valor
    return p2t

In [22]:
def how_hot_is(df, df_base):
    anterior = 0
    prob = []
    prob1 = []
    prob2 = []
    prob3 = []
    better = []
    for index, row in df.iterrows():
        last = int(row[3])
        media = int(row[2])
        moda = str(row[4]) 
        pesos = float(row[7])
        #print("last: ",last," media: ", media, " pesos: ", pesos, " moda: ", moda)
        if ((int(last) > int(0)) & (int(media) > int(0)) ):
            res1 = set_hot_level(last, media)
            p1 = float(res1)
        else:
            p1 = float(0.33)
        prob1.append(p1)
        
        splitedtupla= unsplited_tupla(moda)
        if type(splitedtupla) is not type(moda):
            df_splited = pd.DataFrame(splitedtupla)
            #print("df_splited:", df_splited)
            for index, row in df_splited.iterrows():
                valor = int(row[0])
                res2 = set_hot_level(last, valor)
                better.append(float(res2)) 
            #print("valor de better ", better)
            conteo = len(better)          
            for i in better: 
                temp = float(i) 
                if int(conteo) == int(0):
                    conteo = conteo +1
                    anterior = i
                else:
                    conteo = conteo +1
                    if float(temp) <= float(anterior):
                        anterior = temp
            p2 = retorna_valor(anterior)
        else:
            res2 = set_hot_level(last, moda)
            p2 = retorna_valor(res2)
        prob2.append(p2)        
        
        p3 = pesos
        prob3.append(p3)
        #print("p1: ",p1, "p2: ", p2, "p3: ", p3)
        prob.append(float(p1 + p2 + p3)/ int(3))
    return prob, prob1, prob2, prob3

In [23]:
def procesa_conteo_sbs(conteos, df):
    media = []
    modaa = []
    lasts = []
    delta = []
    resta = []
    for index, row in conteos.iterrows():
        sbs = str(row[1])
        sbs1 = [str(sbs)]
        dftx = df[df.sb.isin(sbs1)]
        df_filt = dftx.iloc[0::1,[0]]
        df_tupla = calcular_deltas_verticales(df_filt)
        lasts.append(df_tupla[0])
        media.append(calc_media(df_tupla))
        resta.append(abs(int(df_tupla[0])- int(calc_media(df_tupla))))
        df_moda = calc_moda(df_tupla)
        pal = '|'.join([str(m) for m in df_moda]) if len(df_moda) > 1  else str(df_moda[0])
        modaa.append(pal)
        #conteos = calc_cant_moda(df_tupla, df_moda)
        palabra = '|'.join([str(e) for e in df_tupla]) 
        delta.append(palabra)        
        #print(sbs, " X", promedio, " L", last, " M", moda," T",  df_tupla)
    dft = conteos
    dft['X'] = media
    dft['L'] = lasts
    dft['R'] = resta    
    dft['M'] = modaa
    dft['T'] = delta
    df_filt2 = dft.iloc[0::1,[0]]
    #print("df_filt2", df_filt2)
    df_pesos = sumarcol_peso(df_filt2)
    #print("valor de df_pesos ", df_pesos)
    
    dft['P'] = df_pesos
    #dft['Pr'], dft['Pr1'],dft['Pr2'],dft['Pr3'] = how_hot_is(dft, df_tr_fu_filt_delta)
    proba, proba1,proba2,proba3 = how_hot_is(dft, df_tr_fu_filt_delta)
    dft['Pr']= proba
    dft['PrX'] = proba1
    dft['PrL'] = proba2
    dft['PrM'] = proba3
    #dft.insert(2, "P", df_pesos, True) 
    return dft

In [24]:
def procesa_conteo_singles(conteos, df):
    media = []
    modaa = []
    lasts = []
    delta = []
    resta = []
    for index, row in conteos.iterrows():
        sbs = str(row[1])
        sbs1 = [str(sbs)]
        dftx = df[df.n1.isin(sbs1) | df.n2.isin(sbs1) |df.n3.isin(sbs1) | df.n4.isin(sbs1) |df.n5.isin(sbs1)]
        df_filt = dftx.iloc[0::1,[0]]
        df_tupla = calcular_deltas_verticales(df_filt)
        lasts.append(df_tupla[0])
        media.append(calc_media(df_tupla))
        resta.append(abs(int(df_tupla[0])- int(calc_media(df_tupla))))
        df_moda = calc_moda(df_tupla)
        pal = '|'.join([str(m) for m in df_moda]) if len(df_moda) > 1  else str(df_moda[0])
        modaa.append(pal)
        #conteos = calc_cant_moda(df_tupla, df_moda)
        palabra = '|'.join([str(e) for e in df_tupla]) 
        delta.append(palabra)        
        #print(sbs, " X", promedio, " L", last, " M", moda," T",  df_tupla)
    dft = conteos
    dft['X'] = media
    dft['L'] = lasts
    dft['R'] = resta  
    dft['M'] = modaa
    dft['T'] = delta
    df_filt2 = dft.iloc[0::1,[0]]
    #print("df_filt2", df_filt2)
    df_pesos = sumarcol_peso(df_filt2)
    #print("valor de df_pesos ", df_pesos)
    
    dft['P'] = df_pesos
    #dft['Pr'], dft['Pr1'],dft['Pr2'],dft['Pr3']  = how_hot_is(dft, df_tr_fu_filt_delta)
    proba, proba1,proba2,proba3 = how_hot_is(dft, df_tr_fu_filt_delta)
    dft['Pr']= proba
    dft['PrX'] = proba1
    dft['PrL'] = proba2
    dft['PrM'] = proba3
    #dft.insert(2, "P", df_pesos, True) 
    return dft

In [25]:
def procesa_conteo_dobles(conteos, df):
    media = []
    modaa = []
    lasts = []
    delta = []
    resta = []
    for index, row in conteos.iterrows():
        sbs = str(row[1])
        splitedtupla= unsplited_tupla(sbs)
        sbs1 = [str(splitedtupla[0])]
        sbs2 = [str(splitedtupla[1])]
        dftx = df[(df.n1.isin(sbs1) | df.n2.isin(sbs1) |df.n3.isin(sbs1) | df.n4.isin(sbs1) |df.n5.isin(sbs1)) 
                & (df.n1.isin(sbs2) | df.n2.isin(sbs2) |df.n3.isin(sbs2) | df.n4.isin(sbs2) |df.n5.isin(sbs2))]
        df_filt = dftx.iloc[0::1,[0]]
        df_tupla = calcular_deltas_verticales(df_filt)
        lasts.append(df_tupla[0])
        media.append(calc_media(df_tupla))
        resta.append(abs(int(df_tupla[0])- int(calc_media(df_tupla))))
        df_moda = calc_moda(df_tupla)
        pal = '|'.join([str(m) for m in df_moda]) if len(df_moda) > 1  else str(df_moda[0])
        modaa.append(pal)
        palabra = '|'.join([str(e) for e in df_tupla]) 
        delta.append(palabra)
    dft = conteos
    #print("IMPRIMO DFT ", dft)
    dft['X'] = media
    dft['L'] = lasts
    dft['R'] = resta    
    dft['M'] = modaa
    df_filt2 = dft.iloc[0::1,[0]]
    #print("df_filt2", df_filt2)
    df_pesos = sumarcol_peso(df_filt2)
    #print("valor de df_pesos ", df_pesos)
    dft['T'] = delta
    dft['P'] = df_pesos
    #dft['Pr'], dft['Pr1'],dft['Pr2'],dft['Pr3']  =how_hot_is(dft, df_tr_fu_filt_delta)
    proba, proba1,proba2,proba3 = how_hot_is(dft, df_tr_fu_filt_delta)
    dft['Pr']= proba
    dft['PrX'] = proba1
    dft['PrL'] = proba2
    dft['PrM'] = proba3
    return dft

In [26]:
def procesa_conteo_triples(conteos, df):
    media = []
    modaa = []
    lasts = []
    delta = []
    resta = []
    for index, row in conteos.iterrows():
        sbs = str(row[1])
        splitedtupla= unsplited_tupla(sbs)
        sbs1 = [str(splitedtupla[0])]
        sbs2 = [str(splitedtupla[1])]
        sbs3 = [str(splitedtupla[2])]
        dftx = df[(df.n1.isin(sbs1) | df.n2.isin(sbs1) |df.n3.isin(sbs1) | df.n4.isin(sbs1) |df.n5.isin(sbs1)) 
                & (df.n1.isin(sbs2) | df.n2.isin(sbs2) |df.n3.isin(sbs2) | df.n4.isin(sbs2) |df.n5.isin(sbs2)) 
                & (df.n1.isin(sbs3) | df.n2.isin(sbs3) |df.n3.isin(sbs3) | df.n4.isin(sbs3) |df.n5.isin(sbs3)) ]
        #print(dftx)
        df_filt = dftx.iloc[0::1,[0]]
        df_tupla = calcular_deltas_verticales(df_filt)
        lasts.append(df_tupla[0])
        media.append(calc_media(df_tupla))
        resta.append(abs(int(df_tupla[0])- int(calc_media(df_tupla))))
        df_moda = calc_moda(df_tupla)
        pal = '|'.join([str(m) for m in df_moda]) if len(df_moda) > 1  else str(df_moda[0])
        modaa.append(pal)
        palabra = '|'.join([str(e) for e in df_tupla]) 
        delta.append(palabra)
    dft = conteos
    dft['X'] = media
    dft['L'] = lasts
    dft['R'] = resta    
    dft['M'] = modaa
    df_filt2 = dft.iloc[0::1,[0]]
    #print("df_filt2", df_filt2)
    df_pesos = sumarcol_peso(df_filt2)
    #print("valor de df_pesos ", df_pesos)
    dft['T'] = delta
    dft['P'] = df_pesos
    #dft['Pr'], dft['Pr1'],dft['Pr2'],dft['Pr3']  = how_hot_is(dft, df_tr_fu_filt_delta)
    proba, proba1,proba2,proba3 = how_hot_is(dft, df_tr_fu_filt_delta)
    dft['Pr']= proba
    dft['PrX'] = proba1
    dft['PrL'] = proba2
    dft['PrM'] = proba3
    return dft

In [27]:
def procesa_conteo_cuartetos(conteos, df):
    media = []
    modaa = []
    lasts = []
    delta = []
    resta = []
    for index, row in conteos.iterrows():
        sbs = str(row[1])
        splitedtupla= unsplited_tupla(sbs)
        sbs1 = [str(splitedtupla[0])]
        sbs2 = [str(splitedtupla[1])]
        sbs3 = [str(splitedtupla[2])]
        sbs4 = [str(splitedtupla[3])]
        dftx = df[(df.n1.isin(sbs1) | df.n2.isin(sbs1) |df.n3.isin(sbs1) | df.n4.isin(sbs1) |df.n5.isin(sbs1)) 
                & (df.n1.isin(sbs2) | df.n2.isin(sbs2) |df.n3.isin(sbs2) | df.n4.isin(sbs2) |df.n5.isin(sbs2)) 
                & (df.n1.isin(sbs3) | df.n2.isin(sbs3) |df.n3.isin(sbs3) | df.n4.isin(sbs3) |df.n5.isin(sbs3))
                & (df.n1.isin(sbs4) | df.n2.isin(sbs4) |df.n3.isin(sbs4) | df.n4.isin(sbs4) |df.n5.isin(sbs4))]
        #print(dftx)
        df_filt = dftx.iloc[0::1,[0]]
        df_tupla = calcular_deltas_verticales(df_filt)
        lasts.append(df_tupla[0])
        media.append(calc_media(df_tupla))
        resta.append(abs(int(df_tupla[0])- int(calc_media(df_tupla))))
        df_moda = calc_moda(df_tupla)
        pal = '|'.join([str(m) for m in df_moda]) if len(df_moda) > 1  else str(df_moda[0])
        modaa.append(pal)
        palabra = '|'.join([str(e) for e in df_tupla]) 
        delta.append(palabra)
    dft = conteos
    dft['X'] = media
    dft['L'] = lasts
    dft['R'] = resta
    dft['M'] = modaa
    df_filt2 = dft.iloc[0::1,[0]]
    #print("df_filt2", df_filt2)
    df_pesos = sumarcol_peso(df_filt2)
    #print("valor de df_pesos ", df_pesos)
    dft['T'] = delta
    dft['P'] = df_pesos
    #dft['Pr'], dft['Pr1'],dft['Pr2'],dft['Pr3']  = how_hot_is(dft, df_tr_fu_filt_delta)
    proba, proba1,proba2,proba3 = how_hot_is(dft, df_tr_fu_filt_delta)
    dft['Pr']= proba
    dft['PrX'] = proba1
    dft['PrL'] = proba2
    dft['PrM'] = proba3
    return dft

In [28]:
def procesa_conteo_quintetos(conteos, df):
    media = []
    modaa = []
    lasts = []
    delta = []  
    resta = []
    for index, row in conteos.iterrows():
        sbs = str(row[1])
        splitedtupla= unsplited_tupla(sbs)
        sbs1 = [str(splitedtupla[0])]
        sbs2 = [str(splitedtupla[1])]
        sbs3 = [str(splitedtupla[2])]
        sbs4 = [str(splitedtupla[3])]
        sbs5 = [str(splitedtupla[4])]
        dftx = df[(df.n1.isin(sbs1) | df.n2.isin(sbs1) |df.n3.isin(sbs1) | df.n4.isin(sbs1) |df.n5.isin(sbs1)) 
                & (df.n1.isin(sbs2) | df.n2.isin(sbs2) |df.n3.isin(sbs2) | df.n4.isin(sbs2) |df.n5.isin(sbs2)) 
                & (df.n1.isin(sbs3) | df.n2.isin(sbs3) |df.n3.isin(sbs3) | df.n4.isin(sbs3) |df.n5.isin(sbs3))
                & (df.n1.isin(sbs4) | df.n2.isin(sbs4) |df.n3.isin(sbs4) | df.n4.isin(sbs4) |df.n5.isin(sbs4))
                & (df.n1.isin(sbs5) | df.n2.isin(sbs5) |df.n3.isin(sbs5) | df.n4.isin(sbs5) |df.n5.isin(sbs5)) ]
        #print(dftx)
        df_filt = dftx.iloc[0::1,[0]]
        df_tupla = calcular_deltas_verticales(df_filt)
        lasts.append(df_tupla[0])
        media.append(calc_media(df_tupla))
        resta.append(abs(int(df_tupla[0])- int(calc_media(df_tupla))))
        df_moda = calc_moda(df_tupla)
        pal = '|'.join([str(m) for m in df_moda]) if len(df_moda) > 1  else str(df_moda[0])
        modaa.append(pal)
        palabra = '|'.join([str(e) for e in df_tupla]) 
        delta.append(palabra)
    dft = conteos
    dft['X'] = media
    dft['L'] = lasts
    dft['R'] = resta
    dft['M'] = modaa
    df_filt2 = dft.iloc[0::1,[0]]
    #print("df_filt2", df_filt2)
    df_pesos = sumarcol_peso(df_filt2)
    #print("valor de df_pesos ", df_pesos)
    dft['T'] = delta
    dft['P'] = df_pesos
    proba, proba1,proba2,proba3 = how_hot_is(dft, df_tr_fu_filt_delta)
    dft['Pr']= proba
    dft['PrX'] = proba1
    dft['PrL'] = proba2
    dft['PrM'] = proba3
    return dft

In [29]:
rangos = [*range(0, 3, 1)]

In [30]:
df_cs_tr_sb = procesa_conteo_sbs(conteos_1d_sb_tr, df_tr_fu_filt_delta)
df_cs_tr_sb = df_cs_tr_sb.sort_values('R',ascending=True)
df_cs_tr_sb_fi = df_cs_tr_sb[df_cs_tr_sb.R.isin(rangos)]
#df_cs_tr_sb_fi

valor de suma  conteo    423
dtype: int64

In [31]:
df_sel_sb_tr = df_cs_tr_sb_fi.iloc[0::1,[1,4]]
df_sel_sb_tr

    tupla  R
10     11  0
2       3  1
14     15  1

In [32]:
df_cs_tr = procesa_conteo_singles(conteos_1d_tr, df_tr_fu_filt_delta)
df_cs_tr = df_cs_tr.sort_values('R',ascending=True)
df_cs_tr_fi = df_cs_tr[df_cs_tr.R.isin(rangos)]

valor de suma  conteo    2115
dtype: int64

In [33]:
df_sel_si_tr = df_cs_tr_fi.iloc[0::1,[1,4]]
df_sel_si_tr

    tupla  R
30     31  1
41     42  2
22     23  2
27     28  2
28     29  2
20     21  2

In [34]:
df_cd_tr = procesa_conteo_dobles(conteos_2d_tr, df_tr_fu_filt_delta)
df_cd_tr = df_cd_tr.sort_values('R',ascending=True)
df_cd_tr_fi = df_cd_tr[df_cd_tr.R.isin(rangos)]
df_cd_tr_fi

valor de suma  conteo    4230
dtype: int64

,conteo,tupla,X,L,R,M,T,P,Pr,PrX,PrL,PrM
517,5,15|39,70,70,0,70|78|1|68|63|142,70|78|1|68|63|142,0.001,0.667,1.000,1.000,0.001
577,4,18|23,84,84,0,84|87|4|188|59,84|87|4|188|59,0.001,0.667,1.000,1.000,0.001
187,5,5|32,70,69,1,69|25|23|7|100|198,69|25|23|7|100|198,0.001,0.667,1.000,1.000,0.001
46,4,2|7,84,85,1,85|21|167|86|63,85|21|167|86|63,0.001,0.667,1.000,1.000,0.001
463,5,13|41,70,71,1,71|24|9|43|100|175,71|24|9|43|100|175,0.001,0.667,1.000,1.000,0.001
392,5,11|32,70,69,1,69|41|149|104|6|53,69|41|149|104|6|53,0.001,0.667,1.000,1.000,0.001
684,5,22|41,70,71,1,71|148|4|73|117|9,71|148|4|73|117|9,0.001,0.667,1.000,1.000,0.001
772,7,27|40,52,51,1,51|17|3|112|98|90|1|50,51|17|3|112|98|90|1|50,0.002,0.667,1.000,1.000,0.002
729,6,25|29,60,61,1,61|48|22|69|154|12|56,61|48|22|69|154|12|56,0.001,0.667,1.000,1.000,0.001
237,3,7|9,105,106,1,106|133|120|63,106|133|120|63,0.001,0.667,1.000,1.000,0.001
787,9,28|40,42,41,1,41|25|23|26|84|29|4|136|3|51,41|25|23|26|84|29|4|136|3|51,0.002,0.667,1.000,1.000,0.002
723,2,24|41,140,141,1,141|6|275,141|6|275,0.000,0.667,1.000,1.000,0.000
451,4,13|29,84,86,2,86|93|173|56|14,86|93|173|56|14,0.001,0.667,1.000,1.000,0.001
837,6,32|40,60,62,2,30,62|121|30|18|30|102|59,0.001,0.667,1.000,1.000,0.001
848,8,33|41,46,44,2,44|132|47|24|17|23|5|57|73,44|132|47|24|17|23|5|57|73,0.002,0.667,1.000,1.000,0.002
817,1,30|43,211,209,2,209|213,209|213,0.000,0.667,1.000,1.000,0.000
75,5,2|36,70,68,2,68|2|80|34|107|131,68|2|80|34|107|131,0.001,0.667,1.000,1.000,0.001
788,8,28|41,46,44,2,44|59|146|92|36|15|22|8|0,44|59|146|92|36|15|22|8|0,0.002,0.667,1.000,1.000,0.002
352,4,10|24,84,82,2,132,82|132|132|34|42,0.001,0.667,1.000,1.000,0.001
87,3,3|8,105,103,2,103|96|81|142,103|96|81|142,0.001,0.667,1.000,1.000,0.001
578,4,18|24,84,82,2,82|7|128|108|97,82|7|128|108|97,0.001,0.667,1.000,1.000,0.001

In [35]:
df_ct_tr = procesa_conteo_triples(conteos_3d_tr, df_tr_fu_filt_delta)
df_ct_tr = df_ct_tr.sort_values('R',ascending=True)
df_ct_tr.tail(25)
#df_ct_tr

valor de suma  conteo    4230
dtype: int64

,conteo,tupla,X,L,R,M,T,P,Pr,PrX,PrL,PrM
1424,1,7|14|20,211,1,210,1|421,1|421,0.000,0.667,1.000,1.000,0.000
2542,1,14|34|41,211,1,210,1|421,1|421,0.000,0.667,1.000,1.000,0.000
3513,1,28|36|37,211,422,211,422|0,422|0,0.000,0.667,1.000,1.000,0.000
1772,1,9|15|25,211,0,211,0|422,0|422,0.000,0.443,0.330,1.000,0.000
1776,1,9|15|33,211,0,211,0|422,0|422,0.000,0.443,0.330,1.000,0.000
3633,1,36|37|41,211,422,211,422|0,422|0,0.000,0.667,1.000,1.000,0.000
3516,1,28|36|41,211,422,211,422|0,422|0,0.000,0.667,1.000,1.000,0.000
3393,1,25|27|33,211,0,211,0|422,0|422,0.000,0.443,0.330,1.000,0.000
1837,1,9|27|33,211,0,211,0|422,0|422,0.000,0.443,0.330,1.000,0.000
2660,1,15|37|41,211,422,211,422|0,422|0,0.000,0.667,1.000,1.000,0.000
2659,1,15|36|41,211,422,211,422|0,422|0,0.000,0.667,1.000,1.000,0.000
2636,1,15|28|37,211,422,211,422|0,422|0,0.000,0.667,1.000,1.000,0.000
2629,1,15|27|33,211,0,211,0|422,0|422,0.000,0.443,0.330,1.000,0.000
2618,1,15|25|33,211,0,211,0|422,0|422,0.000,0.443,0.330,1.000,0.000
2614,1,15|25|27,211,0,211,0|422,0|422,0.000,0.443,0.330,1.000,0.000
2587,2,15|21|26,140,360,220,360|55|7,360|55|7,0.000,0.667,1.000,1.000,0.000
3072,3,20|25|43,105,329,224,329|37|35|21,329|37|35|21,0.001,0.667,1.000,1.000,0.001
2864,2,18|22|39,140,364,224,364|39|19,364|39|19,0.000,0.667,1.000,1.000,0.000
1941,2,10|17|37,140,365,225,365|15|42,365|15|42,0.000,0.667,1.000,1.000,0.000
2376,2,13|20|40,140,368,228,368|40|14,368|40|14,0.000,0.667,1.000,1.000,0.000
3362,2,24|31|33,140,375,235,375|31|16,375|31|16,0.000,0.667,1.000,1.000,0.000
209,2,1|20|43,140,382,242,382|36|4,382|36|4,0.000,0.667,1.000,1.000,0.000
3517,2,28|37|41,140,392,252,392|30|0,392|30|0,0.000,0.667,1.000,1.000,0.000
3245,2,22|32|37,140,393,253,393|10|19,393|10|19,0.000,0.667,1.000,1.000,0.000
2635,2,15|28|36,140,415,275,415|7|0,415|7|0,0.000,0.667,1.000,1.000,0.000

In [36]:
df_cc_tr = procesa_conteo_cuartetos(conteos_4d_tr, df_tr_fu_filt_delta)
df_cc_tr = df_cc_tr.sort_values('tupla',ascending=True)
df_cc_tr.head(25)
#df_cc_tr

valor de suma  conteo    2115
dtype: int64

,conteo,tupla,X,L,R,M,T,P,Pr,PrX,PrL,PrM
1304,1,10|11|15|28,211,139,72,139|283,139|283,0.000,0.667,1.000,1.000,0.000
1305,1,10|11|15|31,211,188,23,188|234,188|234,0.000,0.667,1.000,1.000,0.000
1306,1,10|11|15|35,211,139,72,139|283,139|283,0.000,0.667,1.000,1.000,0.000
1307,1,10|11|15|38,211,188,23,188|234,188|234,0.000,0.667,1.000,1.000,0.000
1308,1,10|11|23|33,211,38,173,38|384,38|384,0.000,0.667,1.000,1.000,0.000
1309,1,10|11|28|35,211,139,72,139|283,139|283,0.000,0.667,1.000,1.000,0.000
1310,1,10|11|31|38,211,188,23,188|234,188|234,0.000,0.667,1.000,1.000,0.000
1311,1,10|11|37|40,211,78,133,78|344,78|344,0.000,0.667,1.000,1.000,0.000
1312,1,10|11|37|41,211,78,133,78|344,78|344,0.000,0.667,1.000,1.000,0.000
1313,1,10|11|40|41,211,78,133,78|344,78|344,0.000,0.667,1.000,1.000,0.000
1314,1,10|12|13|32,211,258,47,258|164,258|164,0.000,0.667,1.000,1.000,0.000
1315,1,10|12|13|38,211,258,47,258|164,258|164,0.000,0.667,1.000,1.000,0.000
1316,1,10|12|16|17,211,318,107,318|104,318|104,0.000,0.667,1.000,1.000,0.000
1317,1,10|12|16|27,211,318,107,318|104,318|104,0.000,0.667,1.000,1.000,0.000
1318,1,10|12|17|27,211,318,107,318|104,318|104,0.000,0.667,1.000,1.000,0.000
1319,1,10|12|18|39,211,229,18,229|193,229|193,0.000,0.667,1.000,1.000,0.000
1320,1,10|12|25|27,211,180,31,180|242,180|242,0.000,0.667,1.000,1.000,0.000
1321,1,10|12|25|41,211,180,31,180|242,180|242,0.000,0.667,1.000,1.000,0.000
1322,1,10|12|27|41,211,180,31,180|242,180|242,0.000,0.667,1.000,1.000,0.000
1323,1,10|12|32|38,211,258,47,258|164,258|164,0.000,0.667,1.000,1.000,0.000
1324,1,10|12|34|35,211,283,72,283|139,283|139,0.000,0.667,1.000,1.000,0.000
1325,1,10|12|34|36,211,283,72,283|139,283|139,0.000,0.667,1.000,1.000,0.000
1326,1,10|12|35|36,211,283,72,283|139,283|139,0.000,0.667,1.000,1.000,0.000
1327,1,10|13|21|38,211,376,165,376|46,376|46,0.000,0.667,1.000,1.000,0.000
1328,1,10|13|22|26,211,96,115,96|326,96|326,0.000,0.667,1.000,1.000,0.000

In [37]:
df_cq_tr = procesa_conteo_quintetos(conteos_5d_tr, df_tr_fu_filt_delta)
df_cq_tr = df_cq_tr.sort_values('tupla',ascending=True)
df_cq_tr.head(25)

valor de suma  conteo    423
dtype: int64

,conteo,tupla,X,L,R,M,T,P,Pr,PrX,PrL,PrM
301,1,10|11|15|28|35,211,139,72,139|283,139|283,0.002,0.667,1.000,1.000,0.002
302,1,10|11|15|31|38,211,188,23,188|234,188|234,0.002,0.667,1.000,1.000,0.002
303,1,10|11|37|40|41,211,78,133,78|344,78|344,0.002,0.667,1.000,1.000,0.002
304,1,10|12|13|32|38,211,258,47,258|164,258|164,0.002,0.667,1.000,1.000,0.002
305,1,10|12|16|17|27,211,318,107,318|104,318|104,0.002,0.667,1.000,1.000,0.002
306,1,10|12|25|27|41,211,180,31,180|242,180|242,0.002,0.667,1.000,1.000,0.002
307,1,10|12|34|35|36,211,283,72,283|139,283|139,0.002,0.667,1.000,1.000,0.002
308,1,10|13|22|26|42,211,96,115,96|326,96|326,0.002,0.667,1.000,1.000,0.002
309,1,10|14|18|20|33,211,327,116,327|95,327|95,0.002,0.667,1.000,1.000,0.002
310,1,10|14|19|39|41,211,244,33,244|178,244|178,0.002,0.667,1.000,1.000,0.002
311,1,10|14|20|21|41,211,272,61,272|150,272|150,0.002,0.667,1.000,1.000,0.002
312,1,10|14|27|35|41,211,198,13,198|224,198|224,0.002,0.667,1.000,1.000,0.002
313,1,10|14|29|30|42,211,246,35,246|176,246|176,0.002,0.667,1.000,1.000,0.002
314,1,10|15|16|29|39,211,149,62,149|273,149|273,0.002,0.667,1.000,1.000,0.002
315,1,10|15|20|32|41,211,129,82,129|293,129|293,0.002,0.667,1.000,1.000,0.002
316,1,10|16|18|35|40,211,402,191,402|20,402|20,0.002,0.667,1.000,1.000,0.002
317,1,10|16|19|23|34,211,379,168,379|43,379|43,0.002,0.667,1.000,1.000,0.002
318,1,10|16|23|31|43,211,24,187,24|398,24|398,0.002,0.667,1.000,1.000,0.002
319,1,10|17|24|29|43,211,214,3,214|208,214|208,0.002,0.667,1.000,1.000,0.002
320,1,10|17|24|37|42,211,380,169,380|42,380|42,0.002,0.667,1.000,1.000,0.002
321,1,10|18|19|36|43,211,316,105,316|106,316|106,0.002,0.667,1.000,1.000,0.002
322,1,10|18|21|24|43,211,82,129,82|340,82|340,0.002,0.667,1.000,1.000,0.002
323,1,10|20|21|34|36,211,75,136,75|347,75|347,0.002,0.667,1.000,1.000,0.002
324,1,10|20|25|28|30,211,185,26,185|237,185|237,0.002,0.667,1.000,1.000,0.002
325,1,10|23|25|26|33,211,336,125,336|86,336|86,0.002,0.667,1.000,1.000,0.002

#### Aqui empiezan los llamados a los calculos de revancha

In [38]:
df_cs_re_sb = procesa_conteo_sbs(conteos_1d_sb_re, df_re_fu_filt_delta)
df_cs_re_sb = df_cs_re_sb.sort_values('R',ascending=True)
df_cs_re_sb_fi = df_cs_re_sb[df_cs_re_sb.R.isin(rangos)]
df_cs_re_fi

valor de suma  conteo    425
dtype: int64

NameError: name 'df_cs_re_fi' is not defined

In [ ]:
df_cs_re = procesa_conteo_singles(conteos_1d_re, df_re_fu_filt_delta)
df_cs_re = df_cs_re.sort_values('R',ascending=True)
df_cs_re_fi = df_cs_re[df_cs_re.R.isin(rangos)]
df_cs_re_fi

In [ ]:
df_cd_re = procesa_conteo_dobles(conteos_2d_re, df_re_fu_filt_delta)
df_cd_re = df_cd_re.sort_values('R',ascending=True)
df_cd_re_fi = df_cd_re[df_cd_re.R.isin(rangos)]
df_cd_tr_fi

In [ ]:
df_ct_re = procesa_conteo_triples(conteos_3d_re, df_re_fu_filt_delta)
df_ct_re = df_ct_re.sort_values('R',ascending=True)
df_ct_re.head(25)

In [ ]:
df_ct_re = procesa_conteo_triples(conteos_3d_re, df_re_fu_filt_delta)
df_ct_re = df_ct_re.sort_values('R',ascending=True)
df_ct_re.tail(25)
#df_ct_re

In [ ]:
df_cc_re = procesa_conteo_cuartetos(conteos_4d_re, df_re_fu_filt_delta)
df_cc_re = df_cc_re.sort_values('tupla',ascending=True)
df_cc_re.head(25)

In [ ]:
df_cq_re = procesa_conteo_quintetos(conteos_5d_re, df_re_fu_filt_delta)
df_cq_re = df_cq_re.sort_values('tupla',ascending=True)
df_cq_re.head(25)

#### Aqui inicia el guardado de los dataframe del sorteo tradicional

In [ ]:
df_cs_tr.to_csv(generaPath('O', 'df_cs_tr.csv'), header=['conteo','tupla','X', 'L', 'M', 'R', 'T', 'P','Pr','PrX', 'PrL','PrM'], index=None, sep=',', mode='w')
df_cd_tr.to_csv(generaPath('O', 'df_cd_tr.csv'), header=['conteo','tupla','X', 'L', 'M', 'R', 'T', 'P','Pr','PrX', 'PrL','PrM'], index=None, sep=',', mode='w')
df_ct_tr.to_csv(generaPath('O', 'df_ct_tr.csv'), header=['conteo','tupla','X', 'L', 'M', 'R', 'T', 'P','Pr','PrX', 'PrL','PrM'], index=None, sep=',', mode='w')
df_cc_tr.to_csv(generaPath('O', 'df_cc_tr.csv'), header=['conteo','tupla','X', 'L', 'M', 'R', 'T', 'P','Pr','PrX', 'PrL','PrM'], index=None, sep=',', mode='w')
df_cq_tr.to_csv(generaPath('O', 'df_cq_tr.csv'), header=['conteo','tupla','X', 'L', 'M', 'R', 'T', 'P','Pr','PrX', 'PrL','PrM'], index=None, sep=',', mode='w')

#### Aqui inicia el guardado de los dataframe del sorteo revancha

In [ ]:
df_cs_re.to_csv(generaPath('O', 'df_cs_re.csv'), header=['conteo','tupla','X', 'L', 'M', 'R', 'T', 'P','Pr','PrX', 'PrL','PrM'], index=None, sep=',', mode='w')
df_cd_re.to_csv(generaPath('O', 'df_cd_re.csv'), header=['conteo','tupla','X', 'L', 'M', 'R', 'T', 'P','Pr','PrX', 'PrL','PrM'], index=None, sep=',', mode='w')
df_ct_re.to_csv(generaPath('O', 'df_ct_re.csv'), header=['conteo','tupla','X', 'L', 'M', 'R', 'T', 'P','Pr','PrX', 'PrL','PrM'], index=None, sep=',', mode='w')
df_cc_re.to_csv(generaPath('O', 'df_cc_re.csv'), header=['conteo','tupla','X', 'L', 'M', 'R', 'T', 'P','Pr','PrX', 'PrL','PrM'], index=None, sep=',', mode='w')
df_cq_re.to_csv(generaPath('O', 'df_cq_re.csv'), header=['conteo','tupla','X', 'L', 'M', 'R', 'T', 'P','Pr','PrX', 'PrL','PrM'], index=None, sep=',', mode='w')

In [ ]:
df_cs_tr_sb.to_csv(generaPath('O', 'df_cs_tr_sb.csv'), header=['conteo','tupla','X', 'L', 'M', 'R', 'T', 'P','Pr','PrX', 'PrL','PrM'], index=None, sep=',', mode='w')
df_cs_re_sb.to_csv(generaPath('O', 'df_cs_re_sb.csv'), header=['conteo','tupla','X', 'L', 'M', 'R', 'T', 'P','Pr','PrX', 'PrL','PrM'], index=None, sep=',', mode='w')

#### El codigo validado ha concluido aquí, lo siguiente  son pruebas de concepto

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
x_s = np.array([1,2,3,1,2,2,3,4,1,2,3,4,1,2,4])
n = len(x_s)

#forma lenta
x_mean = 0
for x in x_s:
    x_mean +=x
x_mean/=n
print(x_mean)

In [ ]:
df_topes2 = conteos_2d_tr.iloc[0::1,[0,1]]
print(df_topes2)
mu = 2.0
sigma_1 = 5.0
sigma_2 = 5.0
muestras_1 = np.random.normal(loc = mu, scale = sigma_1, size = 100)
muestras_2 = np.random.normal(loc = mu, scale = sigma_2, size = 100)
print(type(muestras_1))
#print(muestras_1, muestras_2)

In [ ]:
plt.figure(figsize = (10,8))
plt.hist(muestras_1, bins = 20, alpha = 0.5, label = 'Histograma Muestra 1')
plt.hist(muestras_2, bins = 20, alpha = 0.5, label = 'Histograma Muestra 2')
plt.legend()
plt.grid()
plt.show()